name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  simple-ci:
    name: Simple CI (build + quality)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build + QA tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cppcheck clang-format python3-pip
          python3 -m pip install --upgrade pip
          pip3 install cpplint || true

      - name: Build
        run: |
          g++ --version || true
          g++ -std=c++14 -Wall -Wextra -O2 -o library_system main.cpp

      - name: cppcheck
        run: |
          cppcheck --enable=all --std=c++14 --suppress=missingIncludeSystem --error-exitcode=1 main.cpp

      - name: cpplint
        run: |
          cpplint --filter=-legal/copyright main.cpp || true

      - name: clang-format check
        run: |
          clang-format main.cpp > formatted_main.cpp
          if ! diff -u main.cpp formatted_main.cpp; then
            echo "clang-format mismatch: run clang-format -i main.cpp to fix"
            exit 1
          fi